[build]
  command = "npm run build"
  publish = "dist/portfolio/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*.js"
  [headers.values]
  Content-Type = "application/javascript"

[functions]
  directory = "netlify/functions"